[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.0.1",
    "ddgs>=9.16.0",
    "dotenv>=0.9.9",
    "helium>=7.0.3",
    "hf>=1.31.0",
    "huggingface-hub>=1.31.0",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.5",
    "langchain-openai>=1.6.6",
    "langchain-openrouter>=0.2.9",
    "langfuse>=4.15.2",
    "langgraph>=1.2.12",
    "llama-index>=0.14.25",
    "llama-index-embeddings-huggingface>=0.8.0",
    "llama-index-embeddings-huggingface-api>=0.6.0",
    "llama-index-embeddings-openai>=0.6.0",
    "llama-index-llms-openrouter>=0.6.0",
    "llama-index-utils-workflow>=0.11.0",
    "llama-index-vector-stores-chroma>=0.6.0",
    "nest-asyncio>=1.6.0",
    "numpy>=2.5.3",
    "openinference-instrumentation-smolagents>=0.1.40",
    "openrouter>=0.11.46",
    "opentelemetry-exporter-otlp>=1.44.0",
    "opentelemetry-sdk>=1.44.0",
    "python-dotenv>=1.2.3",
    "rank-bm25>=0.2.2",
    "selenium>=4.49.0",
    "smolagents[all,openai,openrouter]>=1.26.0",
]
